name: Build OracleDB Lambda Layer (Thin mode)

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest
    container: public.ecr.aws/sam/build-python3.12  # Matches Lambda runtime

    steps:
      - name: Build layer
        run: |
          set -e
          mkdir -p /asset/python /asset/out
          python -m pip install --upgrade pip
          pip install --only-binary=:all: -t /asset/python oracledb==3.4.0
          find /asset/python -type d -name "__pycache__" -prune -exec rm -rf {} +
          cd /asset && zip -r /asset/out/oracle_layer.zip python

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oracle_layer_py312
          path: /asset/out/oracle_layer.zip
