name: Build OracleDB Lambda Container Image (Thick mode)

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        run: |
          IMAGE_NAME=oracle-lambda-thick
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REPO_URI=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME

          # Create repo if not exists
          aws ecr describe-repositories --repository-names $IMAGE_NAME || \
            aws ecr create-repository --repository-name $IMAGE_NAME

          # Build image using Lambda base image
          docker build -t $REPO_URI:latest .
          docker push $REPO_URI:latest
