name: Build OracleDB Lambda Layer (x86_64)

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python (match your Lambda runtime!)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # or '3.12' to match your Lambda

      - name: Build layer (Thin mode; wheel only)
        run: |
          set -e
          python -m pip install --upgrade pip
          # Use the prebuilt manylinux wheel, do NOT build from source
          pip install --only-binary=:all: -t python oracledb==3.4.0
          # Trim caches
          find python -type d -name "__pycache__" -prune -exec rm -rf {} +
          zip -r9 oracle_layer_py311_x86_64.zip python

      - name: Upload layer artifact
        uses: actions/upload-artifact@v4
        with:
          name: oracle_layer_py311_x86_64
          path: oracle_layer_py311_x86_64.zip
