name: Build OracleDB Lambda Layer

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install oracledb==3.4.0 --no-binary :all: --target python

      - name: Zip the layer
        run: |
          zip -r9 oracle_layer.zip python

      - name: Upload layer artifact
        uses: actions/upload-artifact@v3
        with:
          name: oracle_layer
          path: oracle_layer.zip
